require 'spec_helper'

describe RSpecStackTraceGenerator do
  describe "stack_trace" do
    it "produces a log of events generated by a test" do
      tracer = RSpecStackTraceGenerator.new
      object = TestClass.new

      stack_trace = tracer.stack_trace { object.invoke_a_method }

      include_a_matching_line(stack_trace, /invoke_a_method/).should be_true
    end

    it "does not log rspec-related set-up or invocations"
  end
end
