require 'spec_helper'

describe StackTraceGenerator do
  describe "enable!" do
    it "turns on the trace function" do
      object = TestClass.new
      tracer = StackTraceGenerator.new

      tracer.enable!
      object.invoke_a_method

      tracer.disable!
      tracer.stack_frames.should_not be_empty
    end
  end

  describe "disable!" do
    it "disables the trace function" do
      object = TestClass.new
      tracer = StackTraceGenerator.new
      tracer.enable!
      object.invoke_a_method

      tracer.disable!
      current_stack_size = tracer.stack_frames.length
      object.invoke_a_method

      tracer.stack_frames.length.should == current_stack_size
    end
  end

  describe "stack_trace" do
    it "produces a log of events generated by a method call" do
      tracer = StackTraceGenerator.new
      object = TestClass.new

      stack_trace = tracer.stack_trace { object.invoke_a_method }

      include_a_matching_line(stack_trace, /invoke_a_method/).should be_true
    end

    it "applies filters to the stack trace" do
      tracer = StackTraceGenerator.new(BadFilter.new)
      object = TestClass.new

      stack_trace = tracer.stack_trace { object.invoke_bad_method }

      include_a_matching_line(stack_trace, /invoke_bad_method/).should_not be_true
    end
  end

  describe "initialize" do
    it "adds the filters to the tracer" do
      tracer = StackTraceGenerator.new(BadFilter.new)
      tracer.filters.length.should == 1
    end

    it "accepts a variable number of arguments" do
      tracer = StackTraceGenerator.new(BadFilter.new, BadFilter.new)
      tracer.filters.length.should == 2
    end
  end
end
